// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvoqagbdfamrwnibwtyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2b3FhZ2JkZmFtcnduaWJ3dHlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MzAwMjIsImV4cCI6MjA1NzIwNjAyMn0.gzJKxEpH0KbKVylPePVfOY6B9a8FfOghfl9HvT52YAc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);